// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using peeposredemption.Infrastructure.Persistence;

#nullable disable

namespace peeposredemption.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315033810_AddBadgeOrbReward")]
    partial class AddBadgeOrbReward
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrbValue")
                        .HasColumnType("bigint")
                        .HasColumnName("orb_value");

                    b.Property<string>("R2Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("r2_key");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("p_k_art_items");

                    b.HasIndex("R2Key")
                        .IsUnique();

                    b.HasIndex("ArtistId", "Rarity");

                    b.ToTable("art_items");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("PayoutEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_email");

                    b.Property<int>("PayoutMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payout_method");

                    b.Property<long>("TotalEarnedCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_earned_cents");

                    b.Property<long>("TotalPaidCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_paid_cents");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_artists");

                    b.HasIndex("PayoutEmail")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtistCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("art_item_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<long>("CommissionCents")
                        .HasColumnType("bigint")
                        .HasColumnName("commission_cents");

                    b.Property<long>("CommissionOrbs")
                        .HasColumnType("bigint")
                        .HasColumnName("commission_orbs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("OrbAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("orb_amount");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_artist_commissions");

                    b.HasIndex("ArtItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("ArtistId", "CreatedAt");

                    b.ToTable("artist_commissions");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtistPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<int>("PayoutMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payout_method");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("p_k_artist_payouts");

                    b.HasIndex("ArtistId");

                    b.ToTable("artist_payouts");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.BadgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrbReward")
                        .HasColumnType("bigint")
                        .HasColumnName("orb_reward");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StatKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat_key");

                    b.Property<long>("Threshold")
                        .HasColumnType("bigint")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("p_k_badge_definitions");

                    b.HasIndex("StatKey", "Threshold");

                    b.ToTable("badge_definitions");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.BannedMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid>("BannedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_user_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_banned_members");

                    b.HasIndex("BannedByUserId");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId");

                    b.ToTable("banned_members");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_channels");

                    b.HasIndex("ServerId");

                    b.ToTable("channels");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.DirectMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("p_k_direct_messages");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("direct_messages");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_friend_requests");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("friend_requests");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("p_k_messages");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChannelId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ModerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModeratorId")
                        .HasColumnType("uuid")
                        .HasColumnName("moderator_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid?>("TargetMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_message_id");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("p_k_moderation_logs");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("ServerId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("moderation_logs");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("FromUserId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbGift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.HasKey("Id")
                        .HasName("p_k_orb_gifts");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("orb_gifts");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrbAmount")
                        .HasColumnType("integer")
                        .HasColumnName("orb_amount");

                    b.Property<long>("PriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_cents");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_orb_purchases");

                    b.HasIndex("UserId");

                    b.ToTable("orb_purchases");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<Guid?>("RelatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_user_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_orb_transactions");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("orb_transactions");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ParentalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccountFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("account_frozen");

                    b.Property<Guid>("ChildUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DmFriendsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("dm_friends_only");

                    b.Property<string>("LinkCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_code");

                    b.Property<Guid?>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_parental_links");

                    b.HasIndex("ChildUserId");

                    b.HasIndex("LinkCode")
                        .IsUnique();

                    b.HasIndex("ParentUserId");

                    b.ToTable("parental_links");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ReferralCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("p_k_referral_codes");

                    b.HasIndex("OwnerId");

                    b.ToTable("referral_codes");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ReferralPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PurchaserId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchaser_id");

                    b.Property<Guid>("ReferralCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_code_id");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_session_id");

                    b.HasKey("Id")
                        .HasName("p_k_referral_purchases");

                    b.HasIndex("PurchaserId");

                    b.HasIndex("ReferralCodeId");

                    b.ToTable("referral_purchases");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("text")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("StorageTier")
                        .HasColumnType("integer")
                        .HasColumnName("storage_tier");

                    b.HasKey("Id")
                        .HasName("p_k_servers");

                    b.HasIndex("OwnerId");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerEmoji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("R2Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("r2_key");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("p_k_server_emojis");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("ServerId", "Name")
                        .IsUnique();

                    b.ToTable("server_emojis");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.HasKey("Id")
                        .HasName("p_k_server_invites");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServerId");

                    b.ToTable("server_invites");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("server_members");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.StorageUpgradePurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_session_id");

                    b.Property<int>("TargetTier")
                        .HasColumnType("integer")
                        .HasColumnName("target_tier");

                    b.HasKey("Id")
                        .HasName("p_k_storage_upgrade_purchases");

                    b.HasIndex("ServerId");

                    b.ToTable("storage_upgrade_purchases");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationtoken")
                        .HasColumnType("text")
                        .HasColumnName("email_confirmationtoken");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<long>("OrbBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("orb_balance");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("ReferredByCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("referred_by_code_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserActivityStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<long>("PeakOrbBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("peak_orb_balance");

                    b.Property<int>("ServersJoined")
                        .HasColumnType("integer")
                        .HasColumnName("servers_joined");

                    b.Property<long>("TotalMessages")
                        .HasColumnType("bigint")
                        .HasColumnName("total_messages");

                    b.Property<long>("TotalOrbsGifted")
                        .HasColumnType("bigint")
                        .HasColumnName("total_orbs_gifted");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_activity_stats");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_activity_stats");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BadgeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_definition_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<bool>("IsDisplayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_displayed");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_badges");

                    b.HasIndex("BadgeDefinitionId");

                    b.HasIndex("UserId", "BadgeDefinitionId")
                        .IsUnique();

                    b.ToTable("user_badges");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserLoginStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateTime?>("LastClaimedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_claimed_date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<DateTime?>("MessageCountDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_count_date");

                    b.Property<int>("MessageCountToday")
                        .HasColumnType("integer")
                        .HasColumnName("message_count_today");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_login_streaks");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_login_streaks");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtItem", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_art_items__artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Artist", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_artists__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtistCommission", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.ArtItem", "ArtItem")
                        .WithMany()
                        .HasForeignKey("ArtItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_commissions_art_items_art_item_id");

                    b.HasOne("peeposredemption.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_commissions_artists_artist_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_commissions__users_user_id");

                    b.Navigation("ArtItem");

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ArtistPayout", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_payouts_artists_artist_id");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.BannedMember", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_banned_members__users_user_id");

                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_banned_members__servers_server_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_banned_members__users_user_id1");

                    b.Navigation("BannedBy");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Channel", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_channels__servers_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.DirectMessage", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedDirectMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("peeposredemption.Domain.Entities.User", "Sender")
                        .WithMany("SentDirectMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_friend_requests__users_receiver_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_friend_requests__users_sender_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Message", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_messages__users_author_id");

                    b.HasOne("peeposredemption.Domain.Entities.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_messages_channels_channel_id");

                    b.Navigation("Author");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ModerationLog", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_moderation_logs__users_moderator_id");

                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_moderation_logs__servers_server_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_moderation_logs__users_target_user_id");

                    b.Navigation("Moderator");

                    b.Navigation("Server");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Notification", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications__users_from_user_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications__users_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbGift", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_orb_gifts__users_recipient_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_orb_gifts__users_sender_id");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbPurchase", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_orb_purchases__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.OrbTransaction", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_orb_transactions__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ParentalLink", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Child")
                        .WithMany("ParentalLinksAsChild")
                        .HasForeignKey("ChildUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("peeposredemption.Domain.Entities.User", "Parent")
                        .WithMany("ParentalLinksAsParent")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ReferralCode", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_referral_codes__users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ReferralPurchase", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Purchaser")
                        .WithMany()
                        .HasForeignKey("PurchaserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_referral_purchases__users_purchaser_id");

                    b.HasOne("peeposredemption.Domain.Entities.ReferralCode", "ReferralCode")
                        .WithMany("Purchases")
                        .HasForeignKey("ReferralCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_referral_purchases_referral_codes_referral_code_id");

                    b.Navigation("Purchaser");

                    b.Navigation("ReferralCode");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_refresh_tokens__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Server", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_servers__users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerEmoji", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany("Emojis")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_server_emojis_servers_server_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_server_emojis__users_uploaded_by_id");

                    b.Navigation("Server");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerInvite", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_server_invites__users_created_by_id");

                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_server_invites_servers_server_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ServerMember", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany("Members")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_server_members_servers_server_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany("ServerMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_server_members__users_user_id");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.StorageUpgradePurchase", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_storage_upgrade_purchases_servers_server_id");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserActivityStats", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_activity_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.BadgeDefinition", "BadgeDefinition")
                        .WithMany()
                        .HasForeignKey("BadgeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_user_badges_badge_definitions_badge_definition_id");

                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_badges_users_user_id");

                    b.Navigation("BadgeDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.UserLoginStreak", b =>
                {
                    b.HasOne("peeposredemption.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_login_streaks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Channel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.ReferralCode", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.Server", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Emojis");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("peeposredemption.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ParentalLinksAsChild");

                    b.Navigation("ParentalLinksAsParent");

                    b.Navigation("ReceivedDirectMessages");

                    b.Navigation("SentDirectMessages");

                    b.Navigation("ServerMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
